---
  - hosts: all
    become: yes
    vars:
      docker_package_state: present
      docker_users: ['vagrant']
      docker_install_compose: false
    roles:
      - ansible-role-docker
    tasks:
      - name: "apt install make"
        apt:
          name: "make"
          state: present
          update_cache: true