# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "linuxcontainer" do | linuxcontainer |
    linuxcontainer.vm.hostname = "linuxcontainer"
    # linuxcontainer.vm.box = "ubuntu/xenial64"
    linuxcontainer.vm.box = "ubuntu/bionic64"
    linuxcontainer.vm.network "private_network", ip: "192.168.99.50"
    linuxcontainer.vm.provision "shell", path: "provision.sh"
    
    linuxcontainer.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    
  end

end
